name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gee
            asset_name: gee-linux-x86_64
          - os: macos-13
            artifact_name: gee
            asset_name: gee-darwin-x86_64
          - os: macos-latest
            artifact_name: gee
            asset_name: gee-darwin-arm64

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add ARM64 target (macOS only)
        if: matrix.os == 'macos-latest' && contains(matrix.asset_name, 'arm64')
        run: rustup target add aarch64-apple-darwin

      - name: Build
        run: |
          if [[ "${{ matrix.asset_name }}" == *"-arm64" ]]; then
            cargo build --release --target aarch64-apple-darwin
          else
            cargo build --release
          fi
        shell: bash

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          if [[ "${{ matrix.asset_name }}" == *"-arm64" ]]; then
            cp target/aarch64-apple-darwin/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          else
            cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          fi
        shell: bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

  update-homebrew-formula:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set binary URLs
        id: set_urls
        run: |
          echo "INTEL_URL=${{ steps.get_release.outputs.browser_download_url }}/gee-darwin-x86_64" >> $GITHUB_OUTPUT
          echo "ARM_URL=${{ steps.get_release.outputs.browser_download_url }}/gee-darwin-arm64" >> $GITHUB_OUTPUT

      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: gee
          formula-path: Formula/gee.rb
          homebrew-tap: SethHorsley/homebrew-tap
          base-branch: main
          download-url: https://github.com/SethHorsley/gee/archive/refs/tags/${{ github.ref_name }}.tar.gz
          custom-variable: |
            intel_url=${{ steps.set_urls.outputs.INTEL_URL }}
            arm_url=${{ steps.set_urls.outputs.ARM_URL }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
