name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gee
            asset_name: gee-linux-x86_64
          - os: macos-13
            artifact_name: gee
            asset_name: gee-darwin-x86_64
          - os: macos-latest
            artifact_name: gee
            asset_name: gee-darwin-arm64
          # - os: windows-latest
          #   artifact_name: gee.exe
          #   asset_name: gee-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add ARM64 target (macOS only)
        if: matrix.os == 'macos-latest' && contains(matrix.asset_name, 'arm64')
        run: rustup target add aarch64-apple-darwin

      - name: Build
        run: |
          if [[ "${{ matrix.asset_name }}" == *"-arm64" ]]; then
            cargo build --release --target aarch64-apple-darwin
          else
            cargo build --release
          fi
        shell: bash

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          if [[ "${{ matrix.asset_name }}" == *"-arm64" ]]; then
            cp target/aarch64-apple-darwin/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          else
            cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          fi
        shell: bash

      # - name: Prepare binary (Windows)
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     Copy-Item target\release\${{ matrix.artifact_name }} -Destination ${{ matrix.asset_name }}
      #   shell: pwsh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - name: Update Homebrew Formula
        if: matrix.os == 'macos-latest' # Only run this step once
        env:
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}

          # Clone homebrew-gee repository
          git clone https://${HOMEBREW_TAP_TOKEN}@github.com/SethHorsley/homebrew-gee.git
          cd homebrew-gee

          # Update formula file
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" Formula/gee.rb

          # Update SHA256 for Intel
          INTEL_SHA=$(shasum -a 256 ../gee-darwin-x86_64 | awk '{print $1}')
          sed -i '' "s/sha256 \".*\" # Replace with SHA256 for Intel binary/sha256 \"$INTEL_SHA\" # Replace with SHA256 for Intel binary/" Formula/gee.rb

          # Update SHA256 for ARM
          ARM_SHA=$(shasum -a 256 ../gee-darwin-arm64 | awk '{print $1}')
          sed -i '' "s/sha256 \".*\" # Replace with SHA256 for ARM binary/sha256 \"$ARM_SHA\" # Replace with SHA256 for ARM binary/" Formula/gee.rb

          # Commit and push changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/gee.rb
          git commit -m "Update gee to version $VERSION"
          git push https://${HOMEBREW_TAP_TOKEN}@github.com/SethHorsley/homebrew-gee.git main
        shell: bash
